[tool.poetry]
authors = ["Caleb Meyer"]
name = "bridge-trainer"
description = ""
package-mode = false
readme = "README.md"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.7.1"
